Ported to Arch

diff --git a/install b/install
--- a/install
+++ b/install
@@ -2,7 +2,7 @@
 #===================================================================================
 # DEBIAN OPENBOX INSTALL SCRIPT
 # FILE: install
-# DESCRIPTION: automatize Openbox installation in Debian 
+# DESCRIPTION: automatize Openbox installation in Debian
 # AUTHOR: Leonardo Marco
 # VERSION: 1.0
 # CREATED: 2020.03.29
@@ -21,14 +21,13 @@ Usage: '$(basename $0)' [-l] [-a <actions>] [-y] [-d] [-h]
    \e[1m-y\e[0m\t\tAuto-answer yes to all actions
    \e[1m-d\e[0m\t\tAuto-answer default to all actions
    \e[1m-h\e[0m\t\tShow this help'
-	exit 0
+	exit $1
 }
-
 
 #=== FUNCTION ======================================================================
 # NAME: ask_action
 # DESCRIPTION: ask for a action and determine if do it or not do
-# EXIT CODE: 
+# EXIT CODE:
 #	0-> do the action
 #	1-> dont do de action
 #===================================================================================
@@ -36,61 +35,80 @@ n=0
 function ask_action() {
 	action="$1"
 	info="$2"
-	default="${3,,}"; default="${default:0:1}"; 
+	default="${3,,}"
+	default="${default:0:1}"
 	[ "$default" != "n" ] && default="y"
-	n=$((n+1))
+	n=$((n + 1))
 
 	# Skip action if not in -a
-	[ "$actions" ] && { echo "$actions" | grep -w "$n" &> /dev/null || return 1; } 
-	
-	
+	[ "$actions" ] && { echo "$actions" | grep -w "$n" &>/dev/null || return 1; }
+
 	[ "$list" ] && echo -e "[$n] $action ($default)" && return 1
 
-	# Show action 
+	# Show action
 	[ "${default,,}" = "y" ] && q="(Y/n)?" || q="(y/N))?"
 	echo -en "\n\e[33m${info}\n\e[39m\e[1m[$n] \e[4m${action}\e[0m $q "
-	
+
 	case "$yes" in
-		allyes) 	q="y"; echo	"$q"					;;
-		default) 	q="$default"; echo "$q"				;;
-		*)	 		read q; q="${q,,}"; q="${q:0:1}"	;;
+	allyes)
+		q="y"
+		echo "$q"
+		;;
+	default)
+		q="$default"
+		echo "$q"
+		;;
+	*)
+		read q
+		q="${q,,}"
+		q="${q:0:1}"
+		;;
 	esac
-	
+
 	[ "$q" != "n" ] && [ "$q" != "y" ] && q="$default"
 	[ "${q,,}" != "n" ] && return 0
 	return 1
 }
 
-
-
 #=== PARAMS ========================================================================
 while getopts ":hlyda:" o; do
 	case "$o" in
-	h)	help 			;;
-	l)	list="true"		;;
-	y)	yes="allyes"	;;
-	d)	yes="default"	;;
-	a)	for a in $(echo "$OPTARG" | tr "," " "); do
+	h) help ;;
+	l) list="true" ;;
+	y) yes="allyes" ;;
+	d) yes="default" ;;
+	a)
+		for a in $(echo "$OPTARG" | tr "," " "); do
 			# Is a range
-			echo "$a" | grep -E "[0-9]"*-"[0-9]" &> /dev/null && actions="$actions $(eval echo {$(echo $a|sed "s/-/../")})"
-			# Is a number 
-			[ "$a" -eq 0 ] &>/dev/null; [ $? -le 1 ] && actions="$actions $a"
-		done			
+			echo "$a" | grep -E "[0-9]"*-"[0-9]" &>/dev/null && actions="$actions $(eval echo {$(echo $a | sed "s/-/../")})"
+			# Is a number
+			[ "$a" -eq 0 ] &>/dev/null
+			[ $? -le 1 ] && actions="$actions $a"
+		done
 		;;
+	*) echo "$(basename "$0"): Invalid flag -- '-$OPTARG'" && help 1 ;;
 	esac
 done
 
-
 #=== CHECKS =======================================================================
 [ ! "$list" ] && [ "$(id -u)" -ne 0 ] && echo "Administrative privileges needed" && exit 1
-if ! cat /etc/*release | grep -i buster &> /dev/null; then
-	echo "Seems you are not running Debian Buster distro"
+if ! cat /etc/*release | grep -Ei "arch|reborn|react" &>/dev/null; then
+	echo "Seems you are not running Arch Linux distro"
 	echo "Some actions may fail. Cross your fingers and press enter..."
-	read
+	read -s # Dont display keys
 fi
 
-
 #=== EXEC-ACTIONS ==================================================================
+# Some packages come from Arch User Repos, and makepkg can not install as root
+# we need to set a temporary folder to be able to compile and install packages from thre
+# as "nobody" (also we need to setup sudoers to let nobody exec makepkg as root)
+mkdir /home/build
+chgrp nobody /home/build
+chmod g+ws /home/build
+setfacl -m u::rwx,g::rwx /home/build
+setfacl -d --set u::rwx,g::rwx,o::- /home/build
+echo "nobody ALL=(ALL) NOPASSWD: ALL" >>/etc/sudoers
+
 base_dir="$(dirname "$(readlink -f "$0")")"
 echo "$PATH" | grep -q sbin || export PATH="/sbin/:/usr/sbin:$PATH"
 n=0
@@ -99,27 +117,28 @@ n=0
 IFS=$'\n\t'
 shopt -s extglob
 for script in \
-	$(ls "$base_dir"/install_*/install.sh 2>/dev/null) \
-	$(ls "$base_dir"/config_*/install.sh 2>/dev/null) \
-	$(ls "$base_dir"/script_*/install.sh 2>/dev/null) \
-	$(ls "$base_dir"/theme_*/install.sh 2>/dev/null) \
-	$(ls "$base_dir"/!(install_*|script_*|config_*|theme_*)/install.sh 2>/dev/null); 
-do
+	"$base_dir"/install_*/install.sh \
+	"$base_dir"/config_*/install.sh \
+	"$base_dir"/script_*/install.sh \
+	"$base_dir"/theme_*/install.sh; do
 	head="$(head -10 "$script")"
 	# Get ACTION field:
 	action="$(echo "$head" | grep "#[[:blank:]]*ACTION:" | sed 's/#[[:blank:]]*ACTION:[[:blank:]]*//')"
 	[ ! "$action" ] && continue
 	# Get INFO field:
 	info="$(echo "$head" | grep "#[[:blank:]]*INFO:" | sed 's/#[[:blank:]]*INFO:[[:blank:]]*//')"
-	# Get DEFAULTfield:
+	# Get DEFAULT field:
 	default="$(echo "$head" | grep "#[[:blank:]]*DEFAULT:" | sed 's/#[[:blank:]]*DEFAULT:[[:blank:]]*//')"
 
 	if ask_action "$action" "$info" "$default"; then
-		bash "$script"		# EXEC SCRIPT
+		bash "$script" # EXEC SCRIPT
 	fi
 done
 
-if [ ! "$list" ] && [ ! "$actions" ] && ask_action "Reboot" "" "y"; then 
+# Remove the temp folder
+rm -rf /home/build
+
+if [ ! "$list" ] && [ ! "$actions" ] && ask_action "Reboot" "" "y"; then
 	reboot
 fi
 echo
diff --git a/script_wifi-manager/wifi-manager b/script_wifi-manager/wifi-manager
--- a/script_wifi-manager/wifi-manager
+++ b/script_wifi-manager/wifi-manager
@@ -11,11 +11,11 @@
 #===================================================================================
 
 #=== GLOBAL VARIABLES DEFINITION ===============================================
-dependences="iwgetid iwlist wpa_supplicant wpa_cli dhclient ip sudo"		# script dependences
-wpa_config="/etc/wpa_supplicant/wpa_supplicant.conf"						# wpa_supplicant file config to use
-unset daemon_enabled														# Empty if not wpa-cli daemon controlled is enabled
-unset iface																	# iface to use
-unset scan_out																# Raw output of scan command
+dependences="iwgetid iwlist wpa_supplicant wpa_cli dhclient ip sudo" # script dependences
+wpa_config="/etc/wpa_supplicant/wpa_supplicant.conf"                 # wpa_supplicant file config to use
+unset daemon_enabled                                                 # Empty if not wpa-cli daemon controlled is enabled
+unset iface                                                          # iface to use
+unset scan_out                                                       # Raw output of scan command
 unset n_networks
 unset addresses
 unset channels
@@ -24,39 +24,33 @@ unset qualities
 unset keys
 declare -A id_networks
 
-
-
-
-
-function wpacli_isstored {
+function wpacli_isstored() {
 	local ssid="$1"
 	wpa_cli -i "$iface" list_networks 2>/dev/null | grep "^[0-9][[:blank:]]" | cut -f2 | grep "^${ssid}$" &>/dev/null
 	return $?
 }
 
-function daemon_getid {
+function daemon_getid() {
 	local ssid="$1"
 	wpa_cli -i $iface list_networks | grep "^[0-9][[:blank:]]" | cut -f1-2 | grep "[[:blank:]]${ssid}$" | cut -f1
 }
 
-
-function wpacli_addnetwork {
+function wpacli_addnetwork() {
 	echo hola
 }
-
 
 #=== FUNCTION ==================================================================
 # NAME: print_signal_bar
 # DESCRIPTION: prints a wifi singal bar from a signal value like 33/70
 # PARAM1: signal like 33/70
 #===============================================================================
-function print_signal_bar {
-    local a=$(echo "$1" | cut -f1 -d "/")
-    local b=$(echo "$1" | cut -f2 -d "/")
-	local p=$((a*100/b))	# Percent
-	
+function print_signal_bar() {
+	local a=$(echo "$1" | cut -f1 -d "/")
+	local b=$(echo "$1" | cut -f2 -d "/")
+	local p=$((a * 100 / b)) # Percent
+
 	if [ "$p" -le 12 ]; then
-		echo "$p%  ____" 
+		echo "$p%  ____"
 	elif [ "$p" -le 37 ]; then
 		echo "$p%  ▂___"
 	elif [ "$p" -le 62 ]; then
@@ -70,77 +64,75 @@ function print_signal_bar {
 	fi
 }
 
-
 #=== FUNCTION ==================================================================
 # NAME: scan
 # DESCRIPTION: scan visible wifi networks ssid and fill arrays: address, channels, qualities, keys and essids
 #===============================================================================
-function scan {
-    IFS2="$IFS"; IFS=$'\n'
+function scan() {
+	IFS2="$IFS"
+	IFS=$'\n'
 
-    [ ! "$(ip link show $iface up)" ] && sudo ip link set dev $iface up
-	
-    echo -e "\e[1mScaning interface $iface...\e[0m"
-    scan_out="$(sudo iwlist $iface scan)"
-    local scan="$(echo "$scan_out" | egrep "Address|ESSID|Quality|Channel|Encryption key")"
-	
-    addresses=($(echo "$scan" | grep Address: | egrep -o "([0-9A-F]{2}:)+[0-9A-F]{2}"))
-    channels=($(echo "$scan" | grep Channel: | cut -f2 -d:))
-    qualities=($(echo "$scan" | grep Quality | egrep -o "[0-9]+/[0-9]+"))
-    keys=($(echo "$scan" | grep "Encryption key" | cut -f 2 -d:))
-    essids=($(echo "$scan" | grep ESSID | cut -f2 -d:))
-    n_networks="${#addresses[*]}"
+	[ ! "$(ip link show $iface up)" ] && sudo ip link set dev $iface up
 
-    # Loop scaned networks for complete empty ssids and sotred array
-    for n in $(seq 0 $((n_networks-1))); do
-    	local addr="${addresses[$n]}"
-        local ssid="${essids[$n]}"
-        ssid="$(echo "$ssid" | cut -f2 -d\")"
-        [ ! "$ssid" ] && ssid="$addr"
-        essids[$n]="$ssid"
+	echo -e "\e[1mScaning interface $iface...\e[0m"
+	scan_out="$(sudo iwlist $iface scan)"
+	local scan="$(echo "$scan_out" | egrep "Address|ESSID|Quality|Channel|Encryption key")"
 
-        # Get saved networks from daemon
-        if [ "$daemon_enabled" ]; then
-        	wpacli_isstored "$ssid" && stored[$n]="*"
-        	id_networks["$ssid"]=$(daemon_getid "$ssid")
-    	fi
-    done
-    IFS="$IFS2"
+	addresses=($(echo "$scan" | grep Address: | egrep -o "([0-9A-F]{2}:)+[0-9A-F]{2}"))
+	channels=($(echo "$scan" | grep Channel: | cut -f2 -d:))
+	qualities=($(echo "$scan" | grep Quality | egrep -o "[0-9]+/[0-9]+"))
+	keys=($(echo "$scan" | grep "Encryption key" | cut -f 2 -d:))
+	essids=($(echo "$scan" | grep ESSID | cut -f2 -d:))
+	n_networks="${#addresses[*]}"
+
+	# Loop scaned networks for complete empty ssids and sotred array
+	for n in $(seq 0 $((n_networks - 1))); do
+		local addr="${addresses[$n]}"
+		local ssid="${essids[$n]}"
+		ssid="$(echo "$ssid" | cut -f2 -d\")"
+		[ ! "$ssid" ] && ssid="$addr"
+		essids[$n]="$ssid"
+
+		# Get saved networks from daemon
+		if [ "$daemon_enabled" ]; then
+			wpacli_isstored "$ssid" && stored[$n]="*"
+			id_networks["$ssid"]=$(daemon_getid "$ssid")
+		fi
+	done
+	IFS="$IFS2"
 }
-
 
 #=== FUNCTION ==================================================================
 # NAME: list
 # DESCRIPTION: print the list of scanned SSIDS and show in columns
 #===============================================================================
-function list {
-    (
-    IFS=$'\n'
-    echo -e "\e[1mNUM␟  SIGNAL␟SSID␟CHANNEL␟ENCRYPT␟SAVED\e[0m"
-    for n in $(seq 0 $((n_networks-1))); do
-		local addr="${addresses[$n]}"
-        local ssid="${essids[$n]}"
-        local channel="${channels[$n]}"
-        local quality="${qualities[$n]}"
-        quality="$(print_signal_bar $quality)"
-        local key="${keys[$n]}"
-       	local saved="${stored[$n]}"
+function list() {
+	(
+		IFS=$'\n'
+		echo -e "\e[1mNUM␟  SIGNAL␟SSID␟CHANNEL␟ENCRYPT␟SAVED\e[0m"
+		for n in $(seq 0 $((n_networks - 1))); do
+			local addr="${addresses[$n]}"
+			local ssid="${essids[$n]}"
+			local channel="${channels[$n]}"
+			local quality="${qualities[$n]}"
+			quality="$(print_signal_bar $quality)"
+			local key="${keys[$n]}"
+			local saved="${stored[$n]}"
 
-       	local ssid_current="$(get_connected-ssid)"
-		[ "$ssid" = "$ssid_current" ] && echo -en "\e[32m\e[1m"
-        echo -e "[$((n+1))]␟$quality␟$ssid␟$channel␟$key␟$saved"
-		[ "$ssid" = "$ssid_current" ] && echo -en "\e[0m"
-    done
-    echo
-    ) | column -t -s "␟"
+			local ssid_current="$(get_connected-ssid)"
+			[ "$ssid" = "$ssid_current" ] && echo -en "\e[32m\e[1m"
+			echo -e "[$((n + 1))]␟$quality␟$ssid␟$channel␟$key␟$saved"
+			[ "$ssid" = "$ssid_current" ] && echo -en "\e[0m"
+		done
+		echo
+	) | column -t -s "␟"
 }
-
 
 #=== FUNCTION ==================================================================
 # NAME: disconnect
 # DESCRIPTION: disconnect current wifi connection and down wlan iface
 #===============================================================================
-function disconnect {
+function disconnect() {
 	echo -e "\n\e[1mDisconnecting $iface interface\e[0m"
 	if [ "$daemon_enabled" ]; then
 		wpa_cli -i "$iface" disconnect
@@ -149,42 +141,37 @@ function disconnect {
 	fi
 
 	sudo dhclient -v -r "$iface"
-	sudo ip link set dev "$iface" down	
+	sudo ip link set dev "$iface" down
 }
 
-
-function get_connected-ssid {
+function get_connected-ssid() {
 	iwgetid $iface | cut -f2 -d: | cut -f2 -d\"
 }
-
 
 #=== FUNCTION ==================================================================
 # NAME: show_status
 # DESCRIPTION: show current status
 #===============================================================================
-function show_status {
+function show_status() {
 	echo
 
-	echo -e "WPA DAEMON CLI \e[1m\e[32mENABLED\e[0m\n" || echo -e "wpa_cli   \e[1m\e[31mDISABLED\e[0m\n"	
+	echo -e "WPA DAEMON CLI \e[1m\e[32mENABLED\e[0m\n" || echo -e "wpa_cli   \e[1m\e[31mDISABLED\e[0m\n"
 	if [ "$daemon_enabled" ]; then
-		wpa_cli -i "$iface" status | egrep  --color=auto -e ^ -e "^ip_address" -e "^ssid" -e "^wpa_state"
-	else 
+		wpa_cli -i "$iface" status | egrep --color=auto -e ^ -e "^ip_address" -e "^ssid" -e "^wpa_state"
+	else
 		iwgetid "$iface"
 		echo
 		ip -c a show dev $iface
 	fi
 }
 
-
-function show_info {
-	local n="$((${1}-1))"
+function show_info() {
+	local n="$((${1} - 1))"
 	local a="${addresses[$n]}"
 	echo "$scan_out" | sed -n "/Address: ${a}/,/Address/p" | head -n -1 | grep -v "Unknown" | egrep --color -e "^" -e "Address|ESSID|Quality|Channel|Encryption key"
 }
 
-
-
-function connect_no-saved {
+function connect_no-saved() {
 	local ssid="$1"
 	local pass="$2"
 
@@ -195,29 +182,24 @@ function connect_no-saved {
 	sudo dhclient -v "$iface"
 }
 
-
-
-
-
-
 #=== FUNCTION ==================================================================
 # NAME: connect
 # DESCRIPTION: connect to ssid and ask for password
 # PARAM1: ssid to connect
 #===============================================================================
-function connect {
-	local n="$((${1}-1))"
+function connect() {
+	local n="$((${1} - 1))"
 	local ssid="${essids[$n]}"
 	local saved="${stored[$n]}"
 	local dn="${id_networks["$ssid"]}"
 
 	# If connected first disconnect
-	[ "$(get_connected-ssid )" ] && disconnect
-	
+	[ "$(get_connected-ssid)" ] && disconnect
+
 	# CONNECT SAVED NETWORK
 	if [ "$saved" ]; then
 		echo -e "\n\e[1mConnecting to saved $ssid ($dn)\e[0m"
-		wpa_cli -i "$iface" select_network "$dn"|| return
+		wpa_cli -i "$iface" select_network "$dn" || return
 
 	# CONNECT DAEMON-NOTSAVED
 	elif [ "$daemon_enabled" ]; then
@@ -233,7 +215,7 @@ function connect {
 
 		# Save password?
 		unset q
-		while [ "${q,,}" != "n" ]  && [ "${q,,}" != "y" ]; do read -p "Save network? (y/n): " q; done
+		while [ "${q,,}" != "n" ] && [ "${q,,}" != "y" ]; do read -p "Save network? (y/n): " q; done
 		if [ "${q,,}" = "y" ]; then
 			wpa_cli -i "$iface" save_config
 		fi
@@ -244,62 +226,54 @@ function connect {
 		wpa_supplicant -B -i "$iface" -c <(wpa_passphrase "$ssid" "$pass")
 	fi
 
-	# DHCP 
+	# DHCP
 	echo -e "\n\e[1mGetting DHCP address\e[0m"
 	sudo dhclient -v "$iface" || return 1
 }
 
-
-
-
 #=== FUNCTION ==================================================================
-# NAME: init_wpa-daemon 
+# NAME: init_wpa-daemon
 # DESCRIPTION: checks wpa_supplicant daemon is enabled and start it and checks if wpa_cli is enabled
 #===============================================================================
-function init_wpa-daemon {
+function init_wpa-daemon() {
 	pgrep wpa_supplicant &>/dev/null || wpa_supplicant -B -i "$iface" -c "$wpa_config"
 	sleep 0.1
 
 	wpa_cli -h >/dev/null && daemon_enabled=1 || daemon_enabled=""
 }
 
-
-
 #=== FUNCTION ==================================================================
 # NAME: check_dependences
 # DESCRIPTION: checks for script dependences and exit if not found any
 #===============================================================================
-function check_dependences {
+function check_dependences() {
 	local deps_err=""
-	
+
 	for d in $dependences; do
 		! which "$d" &>/dev/null && deps_err="$deps_err${deps_err:+" "}$d"
 	done
-	
+
 	[ "$deps_err" ] && error_msg "Missing dependences: $deps_err\nPlease, solve dependences and try it again" 1
-	
+
 	return 0
 }
-
-
 
 #=== FUNCTION ==================================================================
 # NAME: help
 # DESCRIPTION: checks for script dependences and exit if not found any
 #===============================================================================
-function help {
+function help() {
 	echo "Usage $(basename $0) [-h] [-i iface]"
 	exit $1
 }
-
 
 #=== FUNCTION ==================================================================
 # NAME: error
 # DESCRIPTION: show error message and exit
 # PARAM1: msg
-# PARAM2: exit code 
+# PARAM2: exit code
 #===============================================================================
-function error_msg {
+function error_msg() {
 	local msg="$1"
 	local ecode="$2"
 
@@ -307,14 +281,11 @@ function error_msg {
 	[ "$ecode" ] && exit "$ecode"
 }
 
-
-
-
-function get_network_id {
+function get_network_id() {
 	local n="$1"
 
 	# If n number and in range
-	if [ "$n" -le ${#addresses[*]} ]&>/dev/null && [ "$n" -ge 1 ]; then
+	if [ "$n" -le ${#addresses[*]} ] &>/dev/null && [ "$n" -ge 1 ]; then
 		echo "$n"
 		return 0
 	fi
@@ -331,120 +302,121 @@ function get_network_id {
 	return 1
 }
 
-
-
 #=== FUNCTION ==================================================================
 # NAME: main function
 # DESCRIPTION: start function
 #===============================================================================
-function main {
+function main() {
 	# PARAMETERS
 	while getopts ":hi:s:" p; do
 		case $p in
-			h) 	help 0									;;
-			i) 	iface="$OPTARG" 						;;
-			s)	pssid=1; ssid="$OPTARG"				;;
-			\?) error_msg "Unknow option: -$OPTARG" 1	;;
+		h) help 0 ;;
+		i) iface="$OPTARG" ;;
+		s)
+			pssid=1
+			ssid="$OPTARG"
+			;;
+		\?) error_msg "Unknow option: -$OPTARG" 1 ;;
 		esac
 	done
 
-
 	# CHECK DEPENDENCES
 	check_dependences
-	
+
 	# SET GLOBAL VARIABLES VALUES
 	if [ "$iface" ]; then
 		ip a show dev "$iface" >/dev/null || exit 1
-	else 
-    	iface="$(iw dev | awk '$1=="Interface"{print $2}' | head -1)"
-    fi
-	
+	else
+		iface="$(iw dev | awk '$1=="Interface"{print $2}' | head -1)"
+	fi
 
 	# SELECT ACTION
 	action="scan"
-	while true; do 
+	while true; do
 		case "${action,,}" in
-			l|list) 
-				clear
-				list
-				echo
+		l | list)
+			clear
+			list
+			echo
 			;;
-			""|r|rescan|scan)
-				init_wpa-daemon 
-				clear
-				scan
-				list
-				echo
+		"" | r | rescan | scan)
+			init_wpa-daemon
+			clear
+			scan
+			list
+			echo
 			;;
-			d|disconnect) 
-				disconnect
-				echo
+		d | disconnect)
+			disconnect
+			echo
 			;;
-			s|status)
-				show_status
-				echo
+		s | status)
+			show_status
+			echo
 			;;
-			c*|connect)
-				n="$(echo "$action" | awk '{print $2}')"
-				if ! n="$(get_network_id "$n")"; then
-					error_msg "Invalid network id!"
-					continue
-				fi
-				
-				connect "$n"
-				echo
-			;;
-			i*|info*)
-				n="$(echo "$action" | awk '{print $2}')"
-				if ! n="$(get_network_id "$n")"; then
-					error_msg "Invalid network id!"
-					continue
-				fi				
+		c* | connect)
+			n="$(echo "$action" | awk '{print $2}')"
+			if ! n="$(get_network_id "$n")"; then
+				error_msg "Invalid network id!"
+				continue
+			fi
 
-				show_info "$n"
-				echo
-			;; 
-			h|help)
-				echo -e "  \e[1mc\e[0monnect n\t\tConnect to network"
-				echo -e "  \e[1md\e[0misconnect\t\tDisconnect"
-				echo -e "  \e[1mr\e[0mescan\t\tRescan available wifi networks"
-				echo -e "  \e[1ms\e[0mtatus\t\tShow current status connection"
-				echo -e "  \e[1mi\e[0mnfo n\t\tShow network info"
-				echo
-				unset action
+			connect "$n"
+			echo
 			;;
-			q|quit|exit)
-				exit 0
+		i* | info*)
+			n="$(echo "$action" | awk '{print $2}')"
+			if ! n="$(get_network_id "$n")"; then
+				error_msg "Invalid network id!"
+				continue
+			fi
+
+			show_info "$n"
+			echo
 			;;
-			*) echo "Invalid option!"
+		h | help)
+			echo -e "  \e[1mc\e[0monnect n\t\tConnect to network"
+			echo -e "  \e[1md\e[0misconnect\t\tDisconnect"
+			echo -e "  \e[1mr\e[0mescan\t\tRescan available wifi networks"
+			echo -e "  \e[1ms\e[0mtatus\t\tShow current status connection"
+			echo -e "  \e[1mi\e[0mnfo n\t\tShow network info"
+			echo
+			unset action
+			;;
+		q | quit | exit)
+			exit 0
+			;;
+		*)
+			echo "Invalid option!"
 			;;
 		esac
 
-		echo -en "\e[1mAction (h for help)\e[0m: "; read action
+		echo -en "\e[1mAction (h for help)\e[0m: "
+		read action
 	done
 
 }
 
 main "$@"
 
-
-
 ##############3
 
-	# SHOW LIST AND SELECT NETWORK
-	if [ ! "$pssid" ]; then
-	    unset n_selected
-	    while [ ! "$n_selected" ]; do
-	        clear
-	        scan
-	        [ ${#addresses[*]} -eq 0 ] && { sleep 1; continue; }
-	        list
-			while ! ([ "$n_selected" -le ${#addresses[*]} ]&>/dev/null && [ "$n_selected" -ge 1 ]&>/dev/null); do
-				echo
-	        	read -p "Select network: " n_selected
-				[ ! "$n_selected" ] && break
-			done
-	    done
-	    local ssid="${essids[$((n_selected-1))]}"
-	fi
-
+# SHOW LIST AND SELECT NETWORK
+if [ ! "$pssid" ]; then
+	unset n_selected
+	while [ ! "$n_selected" ]; do
+		clear
+		scan
+		[ ${#addresses[*]} -eq 0 ] && {
+			sleep 1
+			continue
+		}
+		list
+		while ! ([ "$n_selected" -le ${#addresses[*]} ] &>/dev/null && [ "$n_selected" -ge 1 ] &>/dev/null); do
+			echo
+			read -p "Select network: " n_selected
+			[ ! "$n_selected" ] && break
+		done
+	done
+	ssid="${essids[$((n_selected - 1))]}"
+fi
